CAUCSE/CAUSW_frontend_V2

src/app/(causw)/layout.tsx
src/app/globals.css
src/entities/layout/NavigationBar.tsx
src/widget/SideBar.tsx

🚩 관련 이슈
- resolve #16 
📋 PR Checklist
- (causw) Folder에 Main Container 생성
- 스크롤 바 디자인 전체 적용
- Navigation Bar & Side Bar 반응형 디자인
📌 유의사항
✅ 테스트 결과
- PC
- Mobile

[CHORE] Implement Main Container

---

next.config.mjs
package-lock.json
src/app/(causw)/board/[boardId]/[postId]/page.tsx
src/app/(causw)/board/[boardId]/page.tsx
src/entities/board/post/ChildCommentCard.tsx
src/entities/board/post/CommentCard.tsx
src/entities/board/post/PostCard.tsx
src/shared/@types/child-comment.d.ts
src/shared/@types/comment.d.ts
src/shared/@types/post.d.ts
src/shared/hooks/stores/useCommentStore.ts
src/shared/hooks/stores/usePostStore.ts
src/shared/hooks/usePostDetail.ts

🚩 관련 이슈
resolve #20 
📋 PR Checklist
- 게시판-게시글 연결
- 변경된 Post, Comment, ChildComment DTO 적용
- 대댓글 생성 API 연동
- 성능 고려하여 대댓글 상태관리 진행
- Post, Comment, ChildComment UI 디자인 디테일 수정
📌 유의사항
✅ 테스트 결과
**화면 UI**
**게시판-게시글 연결**
https://github.com/user-attachments/assets/4cb7d7b8-fedc-4fda-939e-667f00db7293
**대댓글**
https://github.com/user-attachments/assets/43125a79-577b-4f4e-af36-5bef21167b85
**익명 대댓글**
https://github.com/user-attachments/assets/8e9a1d40-3a76-41cc-9d1f-090e9a776054

[FEAT] Adjust Changed Post/Comment/ChildComment API

---

src/app/(causw)/board/[boardId]/[postId]/page.tsx
src/app/(causw)/board/[boardId]/[postId]/result/page.tsx
src/entities/board/post/ChildCommentCard.tsx
src/entities/board/post/CommentCard.tsx
src/entities/board/post/CommentInput.tsx
src/entities/board/post/PostCard.tsx
src/entities/board/post/VotingSection.tsx
src/shared/hooks/stores/post/usePostDetail.ts
src/shared/hooks/stores/post/useVoteDetail.ts

🚩 관련 이슈
📋 PR Checklist
- 댓글 / 대댓글 버그 수정
- 게시글 상태 관리 로딩 설정
- 댓글 엔터 기능
- 파일 저장 기능
📌 유의사항
✅ 테스트 결과

[FEAT] Complete Post

---

src/app/(causw)/board/[boardId]/[postId]/page.tsx
src/entities/board/post/CommentInput.tsx
src/entities/board/post/PostCard.tsx

🚩 관련 이슈
resolve #20 
📋 PR Checklist
- comment enter key로 입력시 api call 2번 발생하는 버그 수정
📌 유의사항
✅ 테스트 결과

[FIX] Poat Create Error

---

src/app/(causw)/board/[boardId]/create/page.tsx
src/app/(causw)/board/create/page.tsx
src/entities/board/create/RoleSelectSection.tsx
src/entities/board/post/CommentInput.tsx
src/shared/@types/board.d.ts
src/shared/hooks/services/AuthService.tsx
src/shared/hooks/services/BoardRscService.tsx
src/shared/hooks/stores/board/useBoardStore.ts

🚩 관련 이슈
resolve #20 
📋 PR Checklist
- 게시판 role 관련 수정사항 반영
- 한국어 댓글 enter로 작성시 event 2번 발생하는 버그 수정
📌 유의사항
✅ 테스트 결과

[feat/#20] 버그 수정

---

src/app/(causw)/setting/management/payer/[councilFeeId]/page.tsx
src/entities/home/setting/management/AdmissionManagementDetailEntities.ts
src/entities/home/setting/management/CircleManagementDetailButtons.tsx
src/entities/home/setting/management/CouncilFeeManagementDetailEntities.tsx
src/shared/@types/setting.d.ts
src/shared/hooks/services/AuthService.tsx
src/shared/hooks/services/UserCouncilFeeService.tsx
src/widget/CouncilFeeButton.tsx
src/widget/CouncilFeeManagementDetail.tsx

🚩 관련 이슈
ex) resolve #36 
📋 PR Checklist
-
-
-
📌 유의사항
✅ 테스트 결과

[FEAT]: 학생회비 납부자 상세 조회 페이지 구현 ( # 36 )

---

src/app/(causw)/setting/management/circle/[id]/[state]/[userId]/page.tsx
src/shared/@types/circle.d.ts
src/shared/hooks/services/CircleService.tsx

🚩 관련 이슈
ex) resolve #35
📋 PR Checklist
- 동아리 신청 개별 조회 페이지 추가
📌 유의사항
✅ 테스트 결과

[FEAT] Check Application Page 

---

src/app/(causw)/board/[boardId]/[postId]/page.tsx
src/app/(causw)/board/[boardId]/page.tsx
src/app/(causw)/circle/[id]/edit/application/page.tsx
src/app/(causw)/setting/my/comments/page.tsx
src/entities/board/form/CircleApplyQuestion.tsx
src/entities/board/postList/PostListHeader.tsx
src/widget/Management.tsx

🚩 관련 이슈
resolve #35 
📋 PR Checklist

[FIX] Setting Router Issue & Circle Application Issue

---

src/entities/application/AcademicRecordInput.tsx

🚩 관련 이슈
📋 PR Checklist
-
-
-
📌 유의사항
✅ 테스트 결과

[FIX]: 회원가입 후 재학 증빙서류 제출 페이지에서 발생하는 오류 수정 ( # 36 )

---

src/app/(causw)/board/[boardId]/[postId]/formInfo/[formId]/page.tsx
src/app/(causw)/board/[boardId]/page.tsx
src/entities/board/postList/PostListHeader.tsx

🚩 관련 이슈
📋 PR Checklist
- 게시판 알림 설정 버튼 삭제
- 타입 에러 해결
-  게시물 투표, 신청서 아이콘 활성/비활성화 설정
📌 유의사항
✅ 테스트 결과

[Fix #21] 개발계 배포 후 추가 수정사항 및 버그 수정 사항 반영

---

src/app/(causw)/setting/management/circle/[id]/[state]/[userId]/page.tsx
src/shared/@types/circle.d.ts
src/shared/hooks/services/CircleRscSevice.tsx
src/shared/hooks/services/CircleService.tsx
src/widget/Management.tsx

🚩 관련 이슈
ex) resolve #35
📋 PR Checklist
-
-
-
📌 유의사항
✅ 테스트 결과

[FIX] Circle Application Error

---

src/app/(causw)/setting/management/attendance/[state]/page.tsx
src/app/(causw)/setting/management/attendance/detail/all/[id]/page.tsx
src/app/(causw)/setting/management/attendance/detail/waiting/[id]/page.tsx
src/app/auth/authorization/page.tsx
src/app/auth/signin/page.tsx
src/entities/layout/NavigationBar.tsx
src/shared/configs/errorCode.ts
src/shared/hooks/services/SettingService.tsx

🚩 관련 이슈
ex) resolve #35
📋 PR Checklist
-
-
-
📌 유의사항
✅ 테스트 결과

[FIX] Implement Attend User Control

---

src/app/(causw)/home/page.tsx
src/app/(causw)/layout.tsx
src/app/auth/signin/page.tsx
src/app/auth/signup/page.tsx
src/app/layout.tsx
src/entities/background/ImageBackground.tsx
src/entities/home/Banner.tsx
src/entities/home/Calendar.tsx
src/entities/home/card/HomeCard.tsx
src/entities/home/setting/management/AdmissionManagementDetailEntities.ts
src/entities/input/FormInput.tsx
src/entities/layout/NavigationBar.tsx
src/shared/@types/home.d.ts
src/shared/hooks/services/AuthRscService.tsx
src/shared/hooks/services/AuthService.tsx
src/shared/hooks/services/HomeRscService.tsx
src/shared/hooks/services/UserService.tsx
src/widget/SideBar.tsx

🚩 관련 이슈
resolve #35 
📋 PR Checklist
- Home & Sign In & Sign Up Page Design Upgrade
- Fix Home API Error
📌 유의사항
✅ 테스트 결과
https://github.com/user-attachments/assets/90e858f7-fa8e-4edf-9638-25410e250c0c
https://github.com/user-attachments/assets/05819844-bae0-4243-88fa-44009cc4b54a

[FEAT] Home & Sign In & Sign Up Page Design Upgrade

---

src/app/(causw)/setting/management/circle/[id]/[state]/[userId]/page.tsx
src/app/auth/signin/page.tsx

🚩 관련 이슈
resolve #35 
📋 PR Checklist
-
-
-
📌 유의사항
✅ 테스트 결과

[FIX] Sign In System & Circle Apply Accept System

---

src/app/(causw)/home/page.tsx
src/entities/home/Banner.tsx
src/entities/home/Calendar.tsx
src/entities/home/setting/EventEditModal.tsx
src/entities/home/setting/NewCalendarModal.tsx

🚩 관련 이슈
ex) resolve #35 
📋 PR Checklist
- complete calendar componenent 
- complete event banner component
-
📌 유의사항
✅ 테스트 결과

[FEAT] Complete Banner & Calendar

---

src/app/(causw)/layout.tsx
src/app/auth/signup/page.tsx
src/app/globals.css
src/entities/index.ts
src/entities/layout/VTwoForm.tsx
src/shared/@types/user.d.ts
src/shared/hooks/services/UserService.tsx
src/shared/hooks/stores/useUserStore.ts

🚩 관련 이슈
Resolve #35
📋 PR Checklist
- Implement Check V2 System 
-
-
📌 유의사항
✅ 테스트 결과

[FEAT] Implement Check V2 System 

---

src/app/(causw)/circle/[id]/page.tsx
src/app/(causw)/home/page.tsx
src/entities/element/CircleApplyButton.tsx
src/entities/element/CircleElement.tsx

🚩 관련 이슈
resolve #35 
📋 PR Checklist
- 글자 깨짐 및 버튼 이동 디자인 수정
-
-
📌 유의사항
✅ 테스트 결과

[DESIGN] Home & Circle Design Update 

---

next.config.mjs
src/app/auth/signin/page.tsx
src/app/auth/signup/page.tsx
src/shared/hooks/services/AuthService.tsx

🚩 관련 이슈
ex) resolve #76 
📋 PR Checklist
- 인증 페이지 이동 시에 로그인 페이지로 이동하는 에러 해결
📌 유의사항
✅ 테스트 결과

[HOTFIX] Signup Process Error

---

src/app/(causw)/board/[boardId]/[postId]/page.tsx
src/app/(causw)/board/[boardId]/create/page.tsx
src/entities/board/post/ChildCommentCard.tsx
src/entities/board/post/CommentCard.tsx
src/entities/board/post/CommentInput.tsx
src/entities/board/post/PostCard.tsx
src/entities/board/post/create/CreatePostFooter.tsx
src/entities/board/post/create/FilePreview.tsx
src/entities/board/post/create/VotingForm.tsx
src/shared/@types/child-comment.d.ts
src/shared/@types/comment.d.ts
src/shared/@types/post.d.ts
src/shared/hooks/stores/post/useChildCommentStore.ts
src/shared/hooks/stores/post/useCommentStore.ts
src/shared/hooks/stores/post/usePostDetail.ts

🚩 관련 이슈
resolve #86 
📋 PR Checklist
📌 유의사항
✅ 테스트 결과
https://github.com/user-attachments/assets/6e13244f-ff9e-4460-b44c-bdbcf2bb347b
https://github.com/user-attachments/assets/a6c3bbdc-e1fc-42c7-85d1-69a23b3c307b
https://github.com/user-attachments/assets/5746e422-6fae-401d-aedb-783527fee293

86 fix postcomment bug fix

---

src/app/(causw)/board/create/page.tsx
src/app/(causw)/board/page.tsx
src/app/(causw)/circle/[id]/board/create/page.tsx
src/app/(causw)/circle/[id]/board/page.tsx
src/entities/board/create/RoleSelectSection.tsx
src/shared/@types/board.d.ts

🚩 관련 이슈
#91 
📋 PR Checklist
📌 유의사항
✅ 테스트 결과
**수정 전**
**수정 후**
**수정 후**

[#91] 게시판 생성 버튼 위치 조정, 동아리 게시판 페이지에서 동아리 게시판이 안보이는 문제 해결

---

src/app/(causw)/setting/updateacademicrecord/page.tsx
src/app/auth/authorization/page.tsx
src/app/auth/signup/page.tsx
src/entities/application/AcademicRecordInput.tsx
src/entities/application/AdmissionApplicationPage.tsx
src/entities/home/setting/management/AdmissionManagementDetailEntities.ts
src/entities/home/setting/management/ManagementDetailButtons.tsx
src/entities/home/setting/management/WarningModal.tsx
src/shared/index.ts
src/shared/ui/noButtonModal.tsx
src/widget/Management.tsx

🚩 관련 이슈
ex) resolve #83 
📋 PR Checklist
> 회원가입 페이지/ 개인 설정 페이지 / 유저 관리 페이지 에러 수정
---------------------------- 회원가입  ------------------------
---------------------------- 유저 관리------------------------
---------------------------- 개인 설정------------------------
📌 유의사항
✅ 테스트 결과
추발 모달 창 모바일 UI 
가입 신청서 거절 메시지 
학번 입학년도 일치여부 검증
재학 증빙 서류 제출 시 사진만 허용하도록 수정 ( 가입신청서 파트도 마찬가지 )

[FIX] Signup Error

---

src/app/(causw)/circle/[id]/edit/page.tsx
src/app/(causw)/circle/[id]/page.tsx
src/app/(causw)/setting/management/attendance/detail/all/[id]/page.tsx
src/app/(causw)/setting/management/payer/add/[userId]/page.tsx
src/app/(causw)/setting/management/payer/add/page.tsx
src/app/(causw)/setting/management/role/[state]/page.tsx
src/app/(causw)/setting/management/user/[state]/page.tsx
src/app/(causw)/setting/mandate/[state]/[id]/page.tsx
src/app/error.tsx
src/entities/layout/NavigationBar.tsx
src/shared/hooks/services/SettingRscService.tsx
src/widget/Management.tsx
src/widget/ManagementDetailInfoTable.tsx

🚩 관련 이슈
Resolve #95 
📋 PR Checklist
- 학생회 & 관리자 & 학생회장 에러 해결
- 동아리 서비스 비활성화
📌 유의사항
✅ 테스트 결과

[FIX] Disable Circle Service & Fix Setting Error

---

src/entities/board/post/PostCard.tsx
src/shared/hooks/stores/post/create/useFileUpload.ts

🚩 관련 이슈
📋 PR Checklist
📌 유의사항
✅ 테스트 결과

94 fix 게시글 댓글 대댓글 관련 qa 버그 수정

---

src/app/auth/signup/page.tsx
src/entities/home/useTerms.tsx
src/widget/AdmissionManagementDetail.tsx
src/widget/ManagementDetailInfoTable.tsx

🚩 관련 이슈
📋 PR Checklist
📌 유의사항
✅ 테스트 결과
- 모바일 뷰 약관 탭 넓이 조절
- 모바일 뷰 유저 정보 탭 디자인 조정
- PC 뷰 유저 정보 탭 글자 크기 조정

[DESIGN] 102 design sign up user info design update

---

src/app/(causw)/board/[boardId]/[postId]/page.tsx
src/entities/board/post/ChildCommentCard.tsx
src/entities/board/post/CommentCard.tsx
src/entities/board/post/CommentInput.tsx

🚩 관련 이슈
📋 PR Checklist
📌 유의사항
✅ 테스트 결과
- 댓글 입력 창 위치 조정 & 게시글, 댓글 border 통일
- 좋아요 에러 핸들링 숫자 문제 해결
https://github.com/user-attachments/assets/d34e9946-eb0f-4744-ba53-e5a240f81766

[DESIGN] 101 design post design update

---

src/app/(causw)/board/[boardId]/[postId]/formInfo/[formId]/page.tsx
src/app/(causw)/board/[boardId]/[postId]/page.tsx
src/app/(causw)/board/[boardId]/[postId]/result/page.tsx
src/app/(causw)/board/[boardId]/create/page.tsx
src/app/(causw)/setting/page.tsx
src/app/(causw)/setting/personal-info/page.tsx
src/app/auth/authorization/page.tsx
src/app/error.tsx
src/entities/board/post/ChildCommentCard.tsx
src/entities/board/post/CommentCard.tsx
src/entities/board/post/PostCard.tsx
src/entities/board/post/VotingSection.tsx
src/entities/board/post/create/VotingForm.tsx
src/entities/home/setting/management/AdmissionManagementDetailEntities.ts
src/entities/index.ts
src/entities/layout/NavigationBar.tsx
src/entities/modal/Modal.tsx
src/shared/hooks/services/AcademicRecordRscService.tsx
src/shared/hooks/services/AuthService.tsx
src/shared/hooks/services/ChildCommentRscService.tsx
src/shared/hooks/services/SettingRscService.tsx
src/shared/hooks/services/SettingService.tsx
src/shared/hooks/services/VoteRscService.tsx
src/shared/hooks/stores/post/usePostDetail.ts
src/widget/AdmissionManagementDetail.tsx
src/widget/ManagementDetailInfoTable.tsx

🚩 관련 이슈
ex) resolve #103 
📋 PR Checklist
-
-
-
📌 유의사항
✅ 테스트 결과

[FEAT] Home Design Update & Implement Image Full Screen Mode

---

firebase-messaging-sw.js
package-lock.json
package.json
public/firebase-message-sw.js
public/service-worker.js
src/app/auth/signin/page.tsx
src/app/layout.tsx
src/shared/configs/permission.ts
src/shared/index.ts

🚩 관련 이슈
Resolve #117
📋 PR Checklist
-
-
-
📌 유의사항
✅ 테스트 결과

[FEAT] Implement Push Alarm Build Test

---

src/shared/hooks/services/AuthService.tsx

🚩 관련 이슈
회원가입 시 발생하는 에러 수정
📋 PR Checklist
-
-
-
📌 유의사항
✅ 테스트 결과

[FIX] signUp 쪽 에러 수정

---

src/app/layout.tsx
src/app/manifest.json

🚩 관련 이슈
회원가입 수정사항 개발계 -> 운영계에도 반영
📋 PR Checklist
-
-
-
📌 유의사항
✅ 테스트 결과

[FIX] 회원가입 수정사항 운영계 반영

---

src/app/auth/signup/page.tsx
src/shared/@types/user.d.ts

🚩 관련 이슈
📋 PR Checklist
- 회원가입 시 전화번호 하이픈 넣는 방식으로 수정
📌 유의사항
✅ 테스트 결과

[CHORE] 회원가입시 발생하는 에러 수정

---

src/app/auth/findpassword/page.tsx
src/entities/board/post/PostCard.tsx
src/widget/board/BoardList.tsx

🚩 관련 이슈
📋 PR Checklist
- 게시판에 다수의 이미지 올릴 경우 스타일 수정 ( 이미지가 게시물 밖으로 나오는 문제 )
- 게시판 이미지 클릭하고 옆으로 넘길 수 있는 기능 추가
- 비밀번호 찾기 placeholder 수정
- 특정 게시판 상단 고정 정렬 추가
📌 유의사항
✅ 테스트 결과

140 fix 게시판 이미지 관련 스타일 수정 및 부가 기능 추가

---

src/app/(causw)/setting/management/attendance/detail/waiting/[id]/page.tsx
src/app/auth/findemail/page.tsx
src/app/auth/findpassword/page.tsx
src/entities/board/post/PostCard.tsx
src/entities/locker/LockerSelect.tsx
src/shared/hooks/lockers/useSelectLocker.ts
src/shared/hooks/services/AuthService.tsx
src/shared/hooks/stores/useFindAccountStore.ts
src/shared/ui/ImageList.tsx
src/shared/ui/ImageViewer.tsx
src/widget/locker/LockerSelectGrid.tsx

🚩 관련 이슈
📋 PR Checklist
- 이미지 뷰 사이즈 관련 처리
- 사물함 클릭 시 표시되도록 디자인 추가
📌 유의사항
✅ 테스트 결과

[CHORE] 이미지 뷰 사이즈 관련 처리

---

src/app/(causw)/setting/management/payer/add/[userId]/page.tsx
src/app/(causw)/setting/management/payer/add/layout.tsx
src/app/error.tsx
src/app/globals.css
src/app/layout.tsx
src/entities/background/VideoBackground.tsx
src/entities/input/FormInput.tsx
src/entities/layout/NavigationBar.tsx
src/shared/hooks/services/SettingRscService.tsx

🚩 관련 이슈
Resolve #149 
📋 PR Checklist
- 로그인 시 영상 전체 화면으로 자동 재생
- 로그인 화면에 비밀번호 창도 표기 제안
- 기획 상에서 변경되어야 하는 부분이라 무시
- 링크된 사이트 접속 후 뒤로 가기 시 화면 비 깨짐
- 납부자 추가 에러 발생 시 성공 메시지
- 추가 구현
- 납부자 추가 UI 개선
- 로그인 시 input 배경 흰색으로 덮히는 것 수정 
📌 유의사항
✅ 테스트 결과

[FEAT] Layout & Sign In & Payer Page

---

src/app/(causw)/setting/home/@modal/(.)event/layout.tsx
src/app/(causw)/setting/home/event/error.tsx
src/app/(causw)/setting/home/event/layout.tsx
src/app/(causw)/setting/home/event/page.tsx
src/entities/home/setting/BannerCard.tsx
src/entities/home/setting/EventEditModal.tsx
src/shared/configs/query-key/eventQueryKey.ts
src/shared/hooks/events/useEditEvent.ts
src/shared/hooks/services/HomeRscService.tsx
src/shared/hooks/services/HomeService.ts
src/shared/hooks/stores/event/useEventStore.ts
src/shared/index.ts

🚩 관련 이슈
#147 
📋 PR Checklist
📌 유의사항
✅ 테스트 결과

[Fix/#147/banner error fix] 배너 최대 등록 개수 초과 시 에러 메세지 미출력 문제 해결

---

src/app/(causw)/board/[boardId]/create/page.tsx
src/app/(causw)/setting/my/comments/error.tsx
src/app/(causw)/setting/my/comments/page.tsx
src/app/(causw)/setting/my/favorite/error.tsx
src/app/(causw)/setting/my/favorite/page.tsx
src/app/(causw)/setting/my/layout.tsx
src/app/(causw)/setting/my/posts/error.tsx
src/app/(causw)/setting/my/posts/page.tsx
src/entities/board/post/create/CreatePostFooter.tsx
src/entities/board/post/create/PostForm.tsx
src/entities/board/postList/PostItem.tsx
src/shared/@types/form.d.ts
src/shared/@types/pagination.d.ts
src/shared/@types/post.d.ts
src/shared/@types/user.d.ts
src/shared/configs/query-key/index.ts
src/shared/configs/query-key/settingQueryKey.ts
src/shared/hooks/posts/usePostInteraction.ts
src/shared/hooks/services/SettingService.tsx
src/shared/index.ts
src/widget/index.ts
src/widget/post/apply/ApplyCreationForm.tsx
src/widget/setting/MyPageHeader.tsx
src/widget/setting/MyPostList.tsx
src/widget/setting/index.ts

🚩 관련 이슈
#147 
📋 PR Checklist
📌 유의사항
✅ 테스트 결과

[fix/#147/setting-my-page] 설정-내가 쓴 글, 댓글, 찜한 글 기본 썸네일 삭제 및 무한스크롤 기능 추가

---

src/app/(causw)/setting/occasion-setting/page.tsx

🚩 관련 이슈
resolve #113
📋 PR Checklist
- 학번을 입력해서 경조사 알림 설정
- 학번 입력은 4자리로 제한
📌 유의사항
- 라우팅: http://localhost:3000/setting/occasion-setting

[FEAT/#130]: 경조사 알림 설정

---

src/app/auth/signin/page.tsx

🚩 관련 이슈
Resolve #162 
📋 PR Checklist
- Sign In 페이지 접근 시 로그인되어 있다면, Home으로 이동
- Home에서 토큰이 유효하지 않다면 토큰을 지우는 과정이 있으므로, 단순히 확인만 하고 넘기면 됨.
1. 로그인 페이지 접근 
2. 토큰 확인 
3. 있으면 홈으로 이동 
4. 유효하지 않음을 확인하고 지움 
5. 다시 로그인 페이지 
6. 토큰이 없으므로 로그인 페이지 유지
📌 유의사항
✅ 테스트 결과

[CHORE] Auth Routing System

---

src/app/(causw)/setting/home/calendar/page.tsx

🚩 관련 이슈
#167 
📋 PR Checklist
-
-
📌 유의사항
✅ 테스트 결과

[HOTFIX/#167] 캘린더 페이지가 빈화면으로 렌더링되는 문제 해결

---

src/entities/board/post/create/VotingForm.tsx
src/shared/hooks/posts/usePostForm.ts

🚩 관련 이슈
📋 PR Checklist
📌 유의사항
✅ 테스트 결과
https://github.com/user-attachments/assets/1a9a2c2b-c978-482d-8e14-358536a6ac27

[FIX] 3차 QA 결과 반영

---

public/.well-known/assetlinks.json

🚩 관련 이슈
📋 PR Checklist
업데이트를 위한 asserklinks.json 수정입니다.
-
-
-
📌 유의사항
✅ 테스트 결과

[DEPLOY] Update assetlinks.json

---

next.config.mjs
src/fsd_entities/user/api/delete.ts
src/fsd_entities/user/api/get.ts
src/fsd_entities/user/api/put.ts
src/fsd_entities/user/model/stores/useMyInfoStore.ts
src/fsd_entities/user/ui/ManageSettings/AdmissionManagementDetail.tsx
src/fsd_entities/user/ui/ManageSettings/CouncilFeeManagementDetail.tsx
src/fsd_entities/user/ui/ManageSettings/ManagementDetailInfoTable.tsx
src/fsd_entities/user/ui/ManageSettings/ManagementPanel.tsx
src/fsd_entities/user/ui/PersonalSettings/MyRecordHeader.tsx
src/fsd_entities/user/ui/PersonalSettings/MyRecordList.tsx
src/fsd_entities/user/ui/PersonalSettings/ProfileForm.tsx
src/fsd_entities/user/ui/PersonalSettings/forms/ProfileEditForm.tsx
src/fsd_widgets/board/ui/BoardList/BoardList.tsx

🚩 관련 이슈
ex) resolve #213 
📋 PR Checklist
- BoardList RSC hook 에러 수정.
- fsd_entities 내부 모든 component dynamic import 적용.
- user/api 내부 환경 변수 에러 해결.
📌 유의사항
✅ 테스트 결과

[HOTFIX] cannot read properties of undefined reading h 에러 대응

---

.gemini/config.yaml
.gemini/styleguide.md

🚩 관련 이슈
#214 
📋 PR Checklist
- Gemini Code Assist 추가
- config.yaml : 기본적인 설정 (자동 리뷰 비활성화 시켰습니다)
- styleguide.md : 현재 동문네트워크 FE 코드 스타일 가이드를 추가해놓았습니다. 추가했으면 좋은 가이드가 있으면 추천 부탁드립니다.
[공식 사이트](https://developers.google.com/gemini-code-assist/docs/review-github-code?hl=ko)
- /gemini : gemini 명령어 리스트 호출
- /gemini review: gemini 코드 리뷰 요청
📌 유의사항
✅ 테스트 결과

[FEAT/#214] Gemini Code Assist 추가 및 리뷰 스타일 설정

---

src/app/(causw)/setting/page.tsx

🚩 관련 이슈
📋 PR Checklist
-1. 내 경조사 목록보기, 내 경조사 신청, 경조사 알림설정, 경조사 관리 순서로 정렬
- 2. 일반 유저는 내 경조사 목록 보기, 내 경조사 신청, 경조사 알림 설정 보이기
-
-
📌 유의사항
✅ 테스트 결과

경조사 관리 메뉴 수정

---

package-lock.json
package.json
src/fsd_entities/banner/ui/BannerCard.tsx
src/fsd_entities/calender/model/useAddCalendarModal.ts
src/fsd_entities/calender/ui/CalendarCard.tsx
src/fsd_shared/ui/CustomSelect.tsx
src/fsd_shared/utils/date.ts
src/fsd_shared/utils/index.ts
src/fsd_widgets/banner/ui/BannerSettingHeader.tsx
src/fsd_widgets/calender/ui/CalendarAddModal.tsx
src/fsd_widgets/calender/ui/CalendarListHeader.tsx
src/shadcn/components/ui/index.ts
src/shadcn/components/ui/select.tsx

🚩 관련 이슈
#239
📋 PR Checklist
- 설정] 홈화면 → 이벤트 배너·캘린더 노출 관련 이슈
📌 유의사항
✅ 테스트 결과
https://github.com/user-attachments/assets/09a8cad6-ba1b-4478-bea3-f96e2c5714df

fix: [설정] 홈화면 → 이벤트 배너·캘린더 노출 관련 이슈 (#239)

---

src/fsd_widgets/calender/ui/CalendarAddModal.tsx

🚩 관련 이슈
#256 
📋 PR Checklist
- 캘린더 등록 시 글자 겹침 발생
📌 유의사항
✅ 테스트 결과

[설정] -> 홈화면 관리 -> 캘린더

---

src/fsd_widgets/ceremony/ui/AdminCeremonyDetail.tsx
src/fsd_widgets/ceremony/ui/CeremonyDetailPage.tsx

🚩 관련 이슈
ex) resolve #253 
📋 PR Checklist
- 학번 null 값이면 /null 없애기
-
-
📌 유의사항
✅ 테스트 결과

경조사 쪽 학번 null값 정리

---

src/fsd_entities/board/model/queries/useCreateNoticeBoard.ts
src/fsd_entities/ceremony/model/useCeremonyDetailData.ts
src/fsd_entities/ceremony/model/useCeremonySettingForm.ts
src/fsd_entities/ceremony/ui/AdmissionYearInput.tsx
src/fsd_shared/@types/ceremony.ts
src/fsd_widgets/ceremony/ui/NotificationSettingWidget.tsx

🚩 관련 이슈
#263 
📋 PR Checklist
- 경조사 등록 신청/경조사 알림 설정 학번 숫자 두자리
- 게시판 생성 후 목록갔을 때 목록 새로고침 안됨
📌 유의사항
✅ 테스트 결과
https://github.com/user-attachments/assets/3755b898-55f5-4786-bbbe-ba7092bae9c1

[Fix] 경조사 생성, 게시판 생성 후 목록 

---

src/app/(causw)/contacts/[userId]/page.tsx
src/app/(causw)/contacts/page.tsx
src/fsd_widgets/profile/ui/ProfileEdit.tsx

🚩 관련 이슈
#269 
📋 PR Checklist
- [회원정보] 운영계 전화번호 없는 회원 대비,
- 동문 수첩 작성 UX
📌 유의사항
✅ 테스트 결과

[FIX] 동문수첩 (전화번호 없는 회원..등)

---

src/app/(causw)/setting/management/attendance/detail/all/[id]/page.tsx
src/fsd_entities/user/api/put.ts
src/fsd_entities/user/model/hooks/index.ts
src/fsd_entities/user/model/hooks/useUpdateUserNote.ts

🚩 관련 이슈
📋 PR Checklist
-관리자 > 학적상태관리 api 로직 리팩 및 로딩/성공했을때 토스트 알림 추가
-
-
📌 유의사항
✅ 테스트 결과

관리자 > 학적상태관리 로딩/성공 토스트 추가

---

src/app/auth/signin/page.tsx
src/fsd_entities/auth/model/hooks/useFindEmailForm.ts
src/fsd_entities/auth/model/hooks/useFindPasswordForm.ts
src/fsd_entities/auth/model/queries/useFindId.ts
src/fsd_entities/auth/model/queries/useFindPassword.ts
src/fsd_entities/auth/model/stores/useFindAccountStore.ts
src/fsd_entities/auth/ui/AuthFormSubmitButton.tsx
src/fsd_entities/auth/ui/AuthInput.tsx
src/fsd_shared/@types/user.d.ts
src/fsd_widgets/auth/ui/FindEmailForm.tsx
src/fsd_widgets/auth/ui/FindEmailResult.tsx
src/fsd_widgets/auth/ui/FindPasswordForm.tsx

🚩 관련 이슈
ex) resolve #282 
📋 PR Checklist
- 아이디/비밀번호 찾기 학번 대신 전화번호로 수정
- 버튼 cursor pointer 추가
📌 유의사항
✅ 테스트 결과

[FIX] 아이디/비밀번호 찾기 수정

---

src/fsd_entities/post/ui/PostCard/PostCardContent.tsx
src/fsd_entities/post/ui/PostDetailContent/PostDetailContent.tsx
src/fsd_widgets/post/ui/PostContentSection/PostContentSection.tsx

🚩 관련 이슈
ex) resolve #284 
📋 PR Checklist
- 게시글 줄바꿈 안되는 문제 해결
- 게시판목록 미리보기 줄바꿈 안되는 문제 해결
-
📌 유의사항
✅ 테스트 결과
| Before | After |
|--------|-------|
| <img src="https://github.com/user-attachments/assets/7089fedb-8ce8-4b25-bba1-ce0036e25c28" width="350"/> | <img width="350" alt="image" src="https://github.com/user-attachments/assets/374b817d-9b09-4f40-b54f-ccce63c95107" /> |
| Before | After |
|--------|-------|
| <img src="https://github.com/user-attachments/assets/88b36055-8af3-4adb-8088-a99a82a453dc" width="350"/> | <img width="350" alt="image" src="https://github.com/user-attachments/assets/f46c58bc-624e-4923-9d15-c3a794a722bf" /> |

[FIX] 추가 수정사항

---

android/app/build.gradle

🚩 관련 이슈
📋 PR Checklist
- 기존에 버전2가 존재해서 버전3으로 수정합니다.
-
-
📌 유의사항
✅ 테스트 결과

[DEPENDENCY] 안드로이드 버전3으로 업데이트

---

package-lock.json
package.json
src/app/(causw)/setting/page.tsx

🚩 관련 이슈
ex) resolve #312 
📋 PR Checklist
- 문의하기 추가
-
-
📌 유의사항
✅ 테스트 결과

[FEAT] 문의하기 메뉴 추가

---

src/fsd_entities/contact/ui/MonthGridView.tsx

#318 
📋 PR Checklist
- 동문수첩 달력 현재 연도까지
📌 유의사항
✅ 테스트 결과
https://github.com/user-attachments/assets/09e59090-379f-48fa-9fcd-9657a35c73b9

[FIX] 동문수첩 달력 현재 연도

---

package-lock.json
package.json
src/fsd_entities/notification/model/usePushNotification.ts

🚩 관련 이슈
📋 PR Checklist
- pwa환경일 때도 푸시알람 로직이 ios 앱으로 인식하는 바람에 생긴 이슈 였습니다. Capacitor.isNativePlatform() 사용해서 분기하는 것으로 수정했습니다.
-
-
📌 유의사항
✅ 테스트 결과

[FIX] PWA알람 안오는 이슈 해결

---

src/entities/contact/model/hooks/useEditProfile.ts
src/entities/post/ui/PostCard/PostCard.tsx
src/shared/ui/Fab.tsx
src/widgets/post/ui/PostCreationFormButtonGrorup/PostCreationFormButtonGroup.tsx

🚩 관련 이슈
📋 PR Checklist
- 신청서 주석
- 게시글이 2줄 이후로 나오는 이슈 처리
- fab에서 아이콘이 중앙으로 가게 수정
📌 유의사항
✅ 테스트 결과

[CHORE] 동문회 UI 수정사항 반영

---

src/entities/contact/ui/ContactCard.tsx
tailwind.config.js

🚩 관련 이슈
📋 PR Checklist
- 동문수첩 폰트, 사이즈 변경
📌 유의사항
✅ 테스트 결과

[CHORE] 동문수첩 폰트, 사이즈 변경

---

src/app/(causw)/home/ClientGate.tsx
src/app/(causw)/home/ClientGraduatePage.tsx
src/app/(causw)/home/ClientPage.tsx
src/app/(causw)/home/error.tsx
src/app/(causw)/home/page.tsx
src/entities/home/api/get.ts
src/entities/home/config/index.ts
src/entities/home/config/queryKey/homeQueryKey.ts
src/entities/home/config/queryKey/index.ts
src/entities/home/model/index.ts
src/entities/home/model/queries/index.ts
src/entities/home/model/queries/useHomeCalendarQuery.ts
src/entities/home/model/queries/useHomeEventQuery.ts
src/entities/home/model/queries/useHomePostsQuery.ts
src/shared/ui/ErrorFallback.tsx
src/shared/ui/index.ts
src/widgets/calendar/ui/Calendar.tsx

🚩 관련 이슈
📋 PR Checklist
- /home 페이지를 SSR -> CSR로 렌더링 방식 변경
- 에러 보여주는 페이지 따로 정의
-
📌 유의사항
✅ 테스트 결과

[HOTFIX] 모바일 환경에서 튕기는 현상 수정

---

src/app/(causw)/setting/page.tsx

🚩 관련 이슈
ex) resolve #374 
📋 PR Checklist
- 동문회 관리자 권한 설정 수정
-
-
📌 유의사항
✅ 테스트 결과

[FIX] 동문회 관리자 권한 설정 수정

---

src/entities/contact/ui/FilterPills.tsx
src/shared/ui/PageWrapper.tsx
src/widgets/board/ui/BoardList/BoardListClient.tsx
src/widgets/contact/ui/ContactList.tsx

🚩 관련 이슈
#369 
📋 PR Checklist
- URL 기반 필터 상태 유지 기능 구현
- 상단 내비바 색상 통일: 현재 홈/동문수첩은 흰색, 게시판/설정은 하늘색·회색 → 모두 흰색으로 변경
- 동문수첩 필터 워딩 수정: "재학상태" → "학적상태"
📌 유의사항
✅ 테스트 결과
https://github.com/user-attachments/assets/586231f9-71d9-4607-8801-3ccb93da00ae

[FIX] 동문수첩 및 내비게이션 관련 UI/UX 개선
